version: '3'

services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    restart: unless-stopped
    environment:
      POSTGRESQL_CONNECTION_URI: 'postgresql://${POSTGRES_USER:-facoffee}:${POSTGRES_PASSWORD:-facoffee}@db:5432/${POSTGRES_DB:-facoffee_auth_db}'
      ACCESS_TOKEN_VALIDITY: 3600
      REFRESH_TOKEN_VALIDITY: 43200
      API_KEYS: ${SUPERTOKENS_API_KEY?api key is required for supertokens}
    ports:
      - 3567:3567
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 80
      SUPERTOKENS_URL: http://supertokens:3567
      SUPERTOKENS_API_KEY: ${SUPERTOKENS_API_KEY?api key is required for supertokens}
      BASE_URL: http://localhost:8080
      BASE_URL_PATH: /auth
      WEBSITE_URL: http://localhost:3000
      WEBSITE_URL_PATH: /auth
    ports:
      - ${PORT:-8080}:80
    restart: unless-stopped
    depends_on:
      supertokens:
        condition: service_healthy
